### ISSUE TITLE
"SELECT * from" a big db

### ISSUE THREAD

**Issue by mbolder** [andreaspfeil/CubeSQL.Python3#1]
Hello,

there seems to an error in the sendRequest function in handling the data stream.
If I select * from a table that is bigger than the buffer size, it returns None. 

Best regards

M.Bolder

**Comment by andreaspfeil** [comment]
Hello Markus,

thanks for your report.

What do you mean: Select * from table that is bigger than buffer size? 

The buffer size is "unlimited", the chunk size is 4096 byte. Do you mean, the result that is produced by your select consists of more than 4096 bytes? Or does it mean, that your query string is longer than 4096 bytes?

Maybe the JSON data that is returned by the server is not good?
Can you reproduce the error also with the official PHP/JSON implementation?
Can you send me the RAW JSON data stream that is in the variable "data" after line 62?

Before I can look further into this, I need more info.

Also, I feel a little bit thirsty… Maybe you can consider buying me a drink while I look into this problem?

By the way, I am from Germany, so maybe you would like to talk in German with me?

Have a great day,
Andreas Pfeil

**Comment by mbolder** [comment]
Hallo,

denke das Problem, liegt an der Größe der abgefragten Tabelle, und der Art wie der while loop mit self.socket.recv unterbrochen wird. Anscheinend sendet der Server hier bei großen Abfragen nicht stets die gleiche Paketgröße oder der Timeout für die Abfrage ist zu klein, denn er wird einfach mitten im Stream unterbrochen. 

Als Workaround habe ich einfach die Funktion sendRequest kopiert und verwende nun die kopierte sendRequest2 Funktion nur für SELECT Abfragen. Hier unterbreche ich den while loop mit  "if str(buf).endswith("}]'"):" So funktioniert auch die Abfrage von großen Tabellen sowie Remote-Servern.

Beste Grüße
Markus Bolder

**Comment by asn** [comment]
> Hallo,
> 
> denke das Problem, liegt an der Größe der abgefragten Tabelle, und der Art wie der while loop mit self.socket.recv unterbrochen wird. Anscheinend sendet der Server hier bei großen Abfragen nicht stets die gleiche Paketgröße oder der Timeout für die Abfrage ist zu klein, denn er wird einfach mitten im Stream unterbrochen.
> 
> Als Workaround habe ich einfach die Funktion sendRequest kopiert und verwende nun die kopierte sendRequest2 Funktion nur für SELECT Abfragen. Hier unterbreche ich den while loop mit "if str(buf).endswith("}]'"):" So funktioniert auch die Abfrage von großen Tabellen sowie Remote-Servern.
> 
> Beste Grüße
> Markus Bolder

Hi, schließe mich Markus hier an. Habe die Chunksize in sendRequest auch deutlich erhöhen müssen. Bei uns kam es sonst zu Verbindungsabbrüchen und offenen Connections auf dem Server. 
Fehlermeldung: json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 15145 (char 15144)

**Comment by andreaspfeil** [comment]
Danke an Markus und Alex für die Rückmeldung, werde am Wochenende einen Patch einspielen, der alle Probleme grundsätzlich beheben sollte. 

Liebe Grüße,
Andreas Pfeil

**Comment by andreaspfeil** [comment]
Let me know if the patch fixes your problems.
